import { Palette, Printer, Factory, Droplet, Image as ImageIcon, Lightbulb, Scissors, Sparkles, Wrench, Zap, Contact, Type, Car, Presentation, Stamp, PartyPopper } from 'lucide-react';
import type {
  ServiceCategory,
  Order,
  OrderStatus,
  QuoteItem,
  ServiceCategoryId,
} from './types';

// ============================================================
// SERVICE CATEGORIES WITH ALL SUB-SERVICES
// ============================================================

export const serviceCategories: ServiceCategory[] = [
  {
    id: 'colour-digital',
    name: 'Colour Digital Printing',
    icon: Palette,
    description: 'High-quality full-colour digital printing on a wide variety of paper stocks and specialty materials.',
    count: 25,
    filterTag: 'digital',
    subServices: [
      { id: 'cdp-350', name: '350 GSM Paper', description: 'Premium heavy card stock' },
      { id: 'cdp-300', name: '300 GSM Paper', description: 'Heavy card stock' },
      { id: 'cdp-250', name: '250 GSM Paper', description: 'Thick card stock' },
      { id: 'cdp-210', name: '210 GSM Paper', description: 'Standard card stock' },
      { id: 'cdp-170', name: '170 GSM Paper', description: 'Medium card stock' },
      { id: 'cdp-130', name: '130 GSM Paper', description: 'Light card stock' },
      { id: 'cdp-100', name: '100 GSM Paper', description: 'Bond paper' },
      { id: 'cdp-90', name: '90 GSM Paper', description: 'Standard office paper' },
      { id: 'cdp-75a4', name: '75 GSM (A4)', description: 'Economy A4' },
      { id: 'cdp-75a3', name: '75 GSM (A3)', description: 'Economy A3' },
      { id: 'cdp-ntr', name: 'NTR Paper', description: 'NTR specialty paper' },
      { id: 'cdp-jk', name: 'JK Excel Bond', description: 'Premium bond paper' },
      { id: 'cdp-art', name: 'Art Paper', description: 'Glossy art paper' },
      { id: 'cdp-tech-matt', name: 'Technova Sticker (210 GSM) Matt', description: 'Matt sticker stock', startingPrice: 5 },
      { id: 'cdp-tech-gloss', name: 'Technova Sticker (225 GSM) Gloss', description: 'Gloss sticker stock', startingPrice: 6 },
      { id: 'cdp-cs133', name: 'CS 133 (250 GSM) Metal Silver', description: 'Metallic silver paper' },
      { id: 'cdp-transparent', name: 'Transparent Paper', description: 'Clear/transparent media' },
      { id: 'cdp-waterproof', name: 'Waterproof Sticker', description: 'Weather-resistant sticker' },
      { id: 'cdp-texture', name: 'Texture Paper', description: 'Embossed texture paper' },
      { id: 'cdp-gt-offwhite', name: 'GT Offwhite A4 Paper', description: 'Warm tone offwhite' },
      { id: 'cdp-gt-camelle', name: 'GT Camelle Offwhite A4 90 GSM', description: 'Camelle offwhite' },
      { id: 'cdp-vc-300', name: 'Visiting Card (300 GSM)', description: 'Business cards on 300 GSM', startingPrice: 250 },
      { id: 'cdp-vc-ntr', name: 'Visiting Card Plastic Coated (NTR)', description: 'Plastic-coated cards', startingPrice: 350 },
      { id: 'cdp-pvc', name: 'PVC Card', description: 'PVC plastic card', startingPrice: 15 },
      { id: 'cdp-party', name: 'Paper Give by Party', description: 'Customer-supplied paper' },
    ],
  },
  {
    id: 'bw-digital',
    name: 'Black & White Digital Printing',
    icon: Printer,
    description: 'Fast, crisp B&W digital printing for documents, books, and office materials on all standard stocks.',
    count: 20,
    filterTag: 'digital',
    subServices: [
      { id: 'bwd-350', name: '350 GSM Paper' },
      { id: 'bwd-300', name: '300 GSM Paper' },
      { id: 'bwd-250', name: '250 GSM Paper' },
      { id: 'bwd-210', name: '210 GSM Paper' },
      { id: 'bwd-170', name: '170 GSM Paper' },
      { id: 'bwd-130', name: '130 GSM Paper' },
      { id: 'bwd-100', name: '100 GSM Paper' },
      { id: 'bwd-90', name: '90 GSM Paper' },
      { id: 'bwd-ntr', name: 'NTR Paper' },
      { id: 'bwd-jk', name: 'JK Excel Bond' },
      { id: 'bwd-art', name: 'Art Paper' },
      { id: 'bwd-tech-matt', name: 'Technova Sticker (210 GSM) Matt' },
      { id: 'bwd-tech-gloss', name: 'Technova Sticker (225 GSM) Gloss' },
      { id: 'bwd-cs133', name: 'CS 133 (250 GSM) Metal Silver' },
      { id: 'bwd-transparent', name: 'Transparent Paper' },
      { id: 'bwd-waterproof', name: 'Waterproof Sticker' },
      { id: 'bwd-texture', name: 'Texture Paper' },
      { id: 'bwd-gt-offwhite', name: 'GT Offwhite A4 Paper' },
      { id: 'bwd-gt-camelle', name: 'GT Camelle Offwhite A4 90 GSM' },
      { id: 'bwd-party', name: 'Paper Give by Party' },
    ],
  },
  {
    id: 'offset',
    name: 'Offset Work',
    icon: Factory,
    description: 'Traditional offset and Riso printing for bulk runs, envelopes, screen printing and multicolour jobs.',
    count: 4,
    filterTag: 'offset',
    subServices: [
      { id: 'off-multi', name: 'Multicolour Printing (As Per Paper)', description: 'Full colour offset runs' },
      { id: 'off-riso', name: 'Offset / Riso Printing (As Per Paper)', description: 'Riso duplicator printing' },
      { id: 'off-envelope', name: 'Envelope Printing', description: 'Custom envelope printing' },
      { id: 'off-screen', name: 'Screen Printing', description: 'Silk screen printing' },
    ],
  },
  {
    id: 'riso-inkjet',
    name: 'Riso Inkjet Colour Printing',
    icon: Droplet,
    description: 'Riso inkjet colour printing with excellent colour reproduction on matt and textured paper stocks.',
    count: 12,
    filterTag: 'digital',
    subServices: [
      { id: 'riso-170', name: '170 GSM Matt Paper' },
      { id: 'riso-130', name: '130 GSM Matt Paper' },
      { id: 'riso-100', name: '100 GSM Matt Paper' },
      { id: 'riso-90', name: '90 GSM Matt Paper' },
      { id: 'riso-75a4', name: '75 GSM (A4)' },
      { id: 'riso-75a3', name: '75 GSM (A3)' },
      { id: 'riso-jk', name: 'JK Excel Bond' },
      { id: 'riso-art', name: 'Art Paper' },
      { id: 'riso-texture', name: 'Texture Paper' },
      { id: 'riso-gt-offwhite', name: 'GT Offwhite A4 Paper' },
      { id: 'riso-gt-camelle', name: 'GT Camelle Offwhite A4 90 GSM' },
      { id: 'riso-party', name: 'Paper Give by Party' },
    ],
  },
  {
    id: 'solvent',
    name: 'Solvent Printing',
    icon: ImageIcon,
    description: 'Large-format solvent printing for flex banners, vinyl, backlit displays, fabric and standees.',
    count: 13,
    filterTag: 'signage',
    subServices: [
      { id: 'sol-normal-flex', name: 'Normal Flex', description: 'Standard flex banner' },
      { id: 'sol-black-back', name: 'Normal Black Back', description: 'Black back flex' },
      { id: 'sol-star-fl', name: 'Star FL', description: 'Star quality flex' },
      { id: 'sol-star-bb', name: 'Star Black Back', description: 'Star quality black back' },
      { id: 'sol-normal-bl', name: 'Normal Backlit', description: 'Backlit flex' },
      { id: 'sol-star-bl', name: 'Star Backlit', description: 'Star backlit flex' },
      { id: 'sol-vinyl-eco', name: 'Vinyl Economy', description: 'Economy vinyl' },
      { id: 'sol-vinyl-brand', name: 'Vinyl Branded', description: 'Branded vinyl' },
      { id: 'sol-gray-vinyl', name: 'Gray Back Vinyl', description: 'Gray back vinyl' },
      { id: 'sol-fabric', name: 'Fabric', description: 'Fabric printing' },
      { id: 'sol-owv', name: 'Lone Way Vision', description: 'One-way vision vinyl' },
      { id: 'sol-standee-36', name: 'Aluminium Roll Up Standee with Printing (3×6)', description: '3×6 ft standee', startingPrice: 1800 },
      { id: 'sol-standee-256', name: 'Aluminium Roll Up Standee with Printing (2.5×6)', description: '2.5×6 ft standee', startingPrice: 1500 },
    ],
  },
  {
    id: 'led-board',
    name: 'LED Board Making',
    icon: Lightbulb,
    description: 'Custom LED illuminated sign boards, acrylic and channel letters, neon and glow sign boards.',
    count: 12,
    filterTag: 'signage',
    subServices: [
      { id: 'led-acr-3d-acp', name: 'Acrylic 3D Letter ACP Sign Board', description: '3D letters on ACP board' },
      { id: 'led-acr-2d-acp', name: 'Acrylic 2D Letter ACP Sign Board', description: '2D letters on ACP board' },
      { id: 'led-acr-3d', name: 'Acrylic 3D Letter', description: 'Standalone 3D acrylic letters' },
      { id: 'led-al-channel', name: 'Aluminium Channel Letter', description: 'Metal channel letters' },
      { id: 'led-ss', name: 'SS Letter', description: 'Stainless steel letters' },
      { id: 'led-ss-gold', name: 'SS Gold Letter', description: 'Gold-finish SS letters' },
      { id: 'led-ss-gold-light', name: 'SS Gold Letter Light', description: 'Illuminated gold SS letters' },
      { id: 'led-golden-border', name: 'Golden Border Letter', description: 'Golden border lettering' },
      { id: 'led-neon', name: 'Neon Letter/Board', description: 'Neon sign / board' },
      { id: 'led-glow-board', name: 'Glow Sign Board (LED Lights)', description: 'LED glow sign board' },
      { id: 'led-glow-uv', name: 'Glow Sign Board on UV Print (LED Lights)', description: 'UV printed LED board' },
      { id: 'led-display', name: 'LED Display Board', description: 'Digital LED display' },
    ],
  },
  {
    id: 'plotter-cutting',
    name: 'Plotter Cutting',
    icon: Scissors,
    description: 'Precision plotter cutting for vinyl letters, frosted glass films, reflective films and more.',
    count: 10,
    filterTag: 'cutting',
    subServices: [
      { id: 'plt-mirror-gold', name: 'Mirror Gold Vinyl', description: 'Mirror gold vinyl cutting' },
      { id: 'plt-golden', name: 'Golden Vinyl', description: 'Golden vinyl cutting' },
      { id: 'plt-colour', name: 'Colour Vinyl', description: 'Coloured vinyl cutting' },
      { id: 'plt-white', name: 'White Vinyl', description: 'White vinyl cutting' },
      { id: 'plt-retro1', name: 'Retro Type/1', description: 'Retro vinyl type 1' },
      { id: 'plt-retro4', name: 'Retro Type/4', description: 'Retro vinyl type 4' },
      { id: 'plt-retro', name: 'Retro Vinyl', description: 'Retro vinyl' },
      { id: 'plt-frosted', name: 'Frosted Vinyl', description: 'Frosted glass vinyl' },
      { id: 'plt-half-cut', name: 'Half Cutting', description: 'Half-cut stickers' },
      { id: 'plt-reflective', name: 'Reflective Sun Control Glass Films', description: 'Reflective window film' },
    ],
  },
  {
    id: 'uv-eco-solvent',
    name: 'UV Eco Solvent Printing',
    icon: Sparkles,
    description: 'Premium UV eco-solvent large-format printing on vinyl, canvas, fabric, wall media and more.',
    count: 27,
    filterTag: 'uv',
    subServices: [
      { id: 'uv-normal-flex', name: 'Normal Flex' },
      { id: 'uv-black-back', name: 'Normal Black Back' },
      { id: 'uv-star-fl', name: 'Star FL' },
      { id: 'uv-star-bb', name: 'Star Black Back' },
      { id: 'uv-normal-bl', name: 'Normal Backlit' },
      { id: 'uv-star-bl', name: 'Star Backlit' },
      { id: 'uv-vinyl-eco', name: 'Vinyl Economy' },
      { id: 'uv-vinyl-brand', name: 'Vinyl Branded' },
      { id: 'uv-gray-vinyl', name: 'Gray Back Vinyl' },
      { id: 'uv-mirror-gold', name: 'Mirror Gold Vinyl' },
      { id: 'uv-reflective-adv', name: 'Reflective Adv. Glow Vinyl' },
      { id: 'uv-silver', name: 'Silver Vinyl' },
      { id: 'uv-retro', name: 'Retro Vinyl' },
      { id: 'uv-map-roll', name: 'Map Roll Paper' },
      { id: 'uv-clear', name: 'Clear/Transparent Vinyl' },
      { id: 'uv-fabric-nrl', name: 'Fabric NRL' },
      { id: 'uv-fabric-bl', name: 'Fabric BL' },
      { id: 'uv-owv', name: 'One Way Vision' },
      { id: 'uv-colour-vinyl', name: 'Colour Vinyl' },
      { id: 'uv-canvas', name: 'Canvas' },
      { id: 'uv-translit', name: 'Translit' },
      { id: 'uv-retro-brand', name: 'Retro Vinyl Branded' },
      { id: 'uv-wall-media', name: 'Wall Media' },
      { id: 'uv-photo-paper', name: 'Photo Paper' },
      { id: 'uv-wall-texture', name: 'Wall Texture' },
      { id: 'uv-standee-36', name: 'Aluminium Roll Up Standee with Printing (3×6)', startingPrice: 2000 },
      { id: 'uv-standee-256', name: 'Aluminium Roll Up Standee with Printing (2.5×6)', startingPrice: 1700 },
    ],
  },
  {
    id: 'other-work',
    name: 'Other Work & Fabrication',
    icon: Wrench,
    description: 'Stamps, binding, foam boards, vehicle branding, trophies, event management and fabrication.',
    count: 38,
    filterTag: 'fabrication',
    subServices: [
      { id: 'oth-frosted', name: 'Frosted Vinyl' },
      { id: 'oth-reflective', name: 'Reflective Sun Control Glass Films' },
      { id: 'oth-stamp-line', name: 'Laser Cut Polymer Stamp (Line)', startingPrice: 350 },
      { id: 'oth-stamp-round', name: 'Laser Cut Polymer Stamp (Round)', startingPrice: 400 },
      { id: 'oth-si-line', name: 'Self Inking Stamp (Line)', startingPrice: 500 },
      { id: 'oth-si-round', name: 'Self Inking Stamp (Round)', startingPrice: 550 },
      { id: 'oth-spiral-bind', name: 'Spiral Binding (Minimum Size)', startingPrice: 60 },
      { id: 'oth-wire-bind', name: 'Wire Binding (Minimum Size)', startingPrice: 70 },
      { id: 'oth-thesis-bind', name: 'Thesis Binding / Hard Binding', startingPrice: 250 },
      { id: 'oth-5mm-foam-sol', name: '5MM Foam Board with Vinyl in Solvent Print' },
      { id: 'oth-3mm-foam-sol', name: '3MM Foam Board with Vinyl in Solvent Print' },
      { id: 'oth-5mm-foam-uv', name: '5MM Foam Board with Vinyl in UV Print' },
      { id: 'oth-3mm-foam-uv', name: '3MM Foam Board with Vinyl in UV Print' },
      { id: 'oth-vehicle', name: 'Vehicle Branding for Promotional' },
      { id: 'oth-iron-nl', name: 'Iron Frame with NL Flex Printing' },
      { id: 'oth-iron-star', name: 'Iron Frame with Star Flex Printing' },
      { id: 'oth-wood-nl', name: 'Wooden Frame with NL Flex Printing' },
      { id: 'oth-wood-star', name: 'Wooden Frame with Star Flex Printing' },
      { id: 'oth-vinyl-paste', name: 'Vinyl Pasting' },
      { id: 'oth-owv-glass', name: 'One Way Vision Glass Pasting' },
      { id: 'oth-vinyl-lam', name: 'Vinyl Lamination (Matt/Gloss)' },
      { id: 'oth-3mm-foam', name: '3MM Foam Board' },
      { id: 'oth-5mm-foam', name: '5MM Foam Board' },
      { id: 'oth-sandwich', name: 'Sandwich Display Board' },
      { id: 'oth-acr-gold-board', name: 'Acrylic Golden Letter Board' },
      { id: 'oth-acr-nameplate', name: 'Acrylic Name Plate', startingPrice: 800 },
      { id: 'oth-acp-iron', name: 'Big ACP Board (Iron Frame)' },
      { id: 'oth-acp-al', name: 'Big ACP Board (Aluminium Frame)' },
      { id: 'oth-badge-60', name: 'Batches 60MM', startingPrice: 25 },
      { id: 'oth-badge-45', name: 'Batches 45MM', startingPrice: 20 },
      { id: 'oth-brass-trophy', name: 'Brass Trophy', startingPrice: 1500 },
      { id: 'oth-acr-gift', name: 'Acrylic Gift Items' },
      { id: 'oth-momento', name: 'Momento Acrylic Trophy', startingPrice: 800 },
      { id: 'oth-event', name: 'Event Management', description: 'Full event branding & management' },
    ],
  },
  {
    id: 'laser-cnc',
    name: 'Laser / CNC Router Work',
    icon: Zap,
    description: 'Precision laser cutting/engraving on acrylic and CNC routing on wood, MDF, WPC and ACP sheets.',
    count: 10,
    filterTag: 'laser',
    subServices: [
      { id: 'cnc-laser-acr-cut', name: 'Laser Acrylic Sheet Cutting (With Material)' },
      { id: 'cnc-laser-acr-eng', name: 'Laser Acrylic Engraving (With Material)' },
      { id: 'cnc-wood-3d', name: 'CNC Wood 3D Cutting (Without Material)' },
      { id: 'cnc-mdf', name: 'CNC MDF Cutting (Without Material) (8mm to 25mm)' },
      { id: 'cnc-wpc', name: 'CNC WPC Cutting (Without Material)' },
      { id: 'cnc-mdf-jali', name: 'CNC MDF Jali Cutting (Without Material)' },
      { id: 'cnc-mdf-3d', name: 'CNC MDF 3D Cutting (Without Material)' },
      { id: 'cnc-acp-letter', name: 'CNC ACP Sheet Letter Cutting (Without Material)' },
      { id: 'cnc-acp-jali', name: 'CNC ACP Sheet Jali Cutting (Without Material)' },
      { id: 'cnc-acp-creative', name: 'CNC ACP Sheet Creative Cutting (Without Material)' },
    ],
  },
];

// ============================================================
// MOCK ORDERS DATA
// ============================================================

const now = new Date();
const daysAgo = (n: number) => new Date(now.getTime() - n * 86400000).toISOString();

export const mockOrders: Order[] = [
  {
    id: '1',
    orderId: 'ORD-2026-1048',
    customer: { name: 'Rahul Sharma', phone: '+91 98765 43210', email: 'rahul.sharma@email.com', address: '42 MG Road, Nagpur' },
    items: [{
      id: 'i1',
      categoryId: 'led-board',
      categoryName: 'LED Board Making',
      serviceName: 'Acrylic 3D Letter ACP Sign Board',
      quantity: 1,
      specifications: '10 ft × 3 ft, Golden finish, LED lighting inside',
      notes: 'Urgent – needed by 5th Oct',
      designFileName: 'logo_rahul_shops.ai',
    }],
    status: 'in_production',
    deliveryMethod: 'delivery',
    quoteAmount: 18500,
    notes: 'Delivery to shop address',
    adminNotes: 'Design approved on call. Production started.',
    createdAt: daysAgo(7),
    updatedAt: daysAgo(2),
    statusHistory: [
      { status: 'quote_requested', timestamp: daysAgo(7) },
      { status: 'quote_sent', timestamp: daysAgo(6), note: 'Sent quote via WhatsApp' },
      { status: 'quote_approved', timestamp: daysAgo(5) },
      { status: 'design_confirmed', timestamp: daysAgo(4) },
      { status: 'in_production', timestamp: daysAgo(2) },
    ],
  },
  {
    id: '2',
    orderId: 'ORD-2026-1042',
    customer: { name: 'Priya Mehta', phone: '+91 87654 32109', email: 'priya.mehta@business.com', address: '18 Civil Lines, Nagpur' },
    items: [{
      id: 'i2',
      categoryId: 'colour-digital',
      categoryName: 'Colour Digital Printing',
      serviceName: 'Visiting Card (300 GSM)',
      quantity: 500,
      specifications: 'Double sided, Matt lamination',
      notes: '',
      designFileName: 'visiting_card_priya.pdf',
    }],
    status: 'ready',
    deliveryMethod: 'pickup',
    quoteAmount: 800,
    notes: 'Will pick up from shop',
    adminNotes: 'Printed and ready.',
    createdAt: daysAgo(10),
    updatedAt: daysAgo(1),
    statusHistory: [
      { status: 'quote_requested', timestamp: daysAgo(10) },
      { status: 'quote_sent', timestamp: daysAgo(9) },
      { status: 'quote_approved', timestamp: daysAgo(8) },
      { status: 'design_confirmed', timestamp: daysAgo(7) },
      { status: 'in_production', timestamp: daysAgo(5) },
      { status: 'ready', timestamp: daysAgo(1) },
    ],
  },
  {
    id: '3',
    orderId: 'ORD-2026-1037',
    customer: { name: 'Amit Tiwari', phone: '+91 76543 21098', email: 'amit@tiwaritraders.com' },
    items: [
      {
        id: 'i3a',
        categoryId: 'uv-eco-solvent',
        categoryName: 'UV Eco Solvent Printing',
        serviceName: 'Vinyl Branded',
        quantity: 10,
        specifications: '4 ft × 8 ft each, outdoor use',
        notes: '',
        designFileName: 'banner_design.pdf',
      },
      {
        id: 'i3b',
        categoryId: 'solvent',
        categoryName: 'Solvent Printing',
        serviceName: 'Aluminium Roll Up Standee with Printing (3×6)',
        quantity: 2,
        specifications: '3 ft × 6 ft standees',
        notes: 'Required for event',
      },
    ],
    status: 'completed',
    deliveryMethod: 'delivery',
    quoteAmount: 12500,
    notes: 'Event banners for Diwali exhibition',
    adminNotes: 'Delivered successfully',
    createdAt: daysAgo(20),
    updatedAt: daysAgo(5),
    statusHistory: [
      { status: 'quote_requested', timestamp: daysAgo(20) },
      { status: 'quote_sent', timestamp: daysAgo(19) },
      { status: 'quote_approved', timestamp: daysAgo(18) },
      { status: 'design_confirmed', timestamp: daysAgo(17) },
      { status: 'in_production', timestamp: daysAgo(14) },
      { status: 'ready', timestamp: daysAgo(7) },
      { status: 'completed', timestamp: daysAgo(5) },
    ],
  },
  {
    id: '4',
    orderId: 'ORD-2026-1033',
    customer: { name: 'Sunita Agarwal', phone: '+91 65432 10987', email: 'sunita.ag@gmail.com' },
    items: [{
      id: 'i4',
      categoryId: 'laser-cnc',
      categoryName: 'Laser / CNC Router Work',
      serviceName: 'CNC MDF Cutting (Without Material) (8mm to 25mm)',
      quantity: 5,
      specifications: 'Custom wall art design, 4mm MDF, 3 ft × 2 ft each',
      notes: 'DXF file attached',
      designFileName: 'wall_art_dxf.dxf',
    }],
    status: 'quote_sent',
    deliveryMethod: 'pickup',
    estimatedAmount: 7500,
    notes: '',
    adminNotes: 'Quoted ₹7500, awaiting approval',
    createdAt: daysAgo(3),
    updatedAt: daysAgo(1),
    statusHistory: [
      { status: 'quote_requested', timestamp: daysAgo(3) },
      { status: 'quote_sent', timestamp: daysAgo(1) },
    ],
  },
  {
    id: '5',
    orderId: 'ORD-2026-1029',
    customer: { name: 'Rohit Desai', phone: '+91 54321 09876', email: 'rohit@desaibuilders.com' },
    items: [{
      id: 'i5',
      categoryId: 'other-work',
      categoryName: 'Other Work & Fabrication',
      serviceName: 'Vehicle Branding for Promotional',
      quantity: 3,
      specifications: 'Full body wrap on 3 delivery vans, company logo + product images',
      notes: 'Vehicles to be brought to shop',
      designFileName: 'van_branding_design.ai',
    }],
    status: 'quote_approved',
    deliveryMethod: 'pickup',
    quoteAmount: 45000,
    notes: 'All 3 vehicles',
    adminNotes: 'Quote approved, scheduling design confirmation',
    createdAt: daysAgo(5),
    updatedAt: daysAgo(2),
    statusHistory: [
      { status: 'quote_requested', timestamp: daysAgo(5) },
      { status: 'quote_sent', timestamp: daysAgo(4) },
      { status: 'quote_approved', timestamp: daysAgo(2) },
    ],
  },
  {
    id: '6',
    orderId: 'ORD-2026-1024',
    customer: { name: 'Kavita Joshi', phone: '+91 98123 45678', email: 'kavita.joshi@law.com' },
    items: [{
      id: 'i6',
      categoryId: 'other-work',
      categoryName: 'Other Work & Fabrication',
      serviceName: 'Thesis Binding / Hard Binding',
      quantity: 4,
      specifications: 'A4, 400 pages each, hard binding, golden embossing on cover',
      notes: 'PhD thesis – 4 copies',
    }],
    status: 'completed',
    deliveryMethod: 'pickup',
    quoteAmount: 2400,
    notes: '',
    adminNotes: 'Completed',
    createdAt: daysAgo(30),
    updatedAt: daysAgo(25),
    statusHistory: [
      { status: 'quote_requested', timestamp: daysAgo(30) },
      { status: 'quote_sent', timestamp: daysAgo(29) },
      { status: 'quote_approved', timestamp: daysAgo(28) },
      { status: 'design_confirmed', timestamp: daysAgo(27) },
      { status: 'in_production', timestamp: daysAgo(27) },
      { status: 'ready', timestamp: daysAgo(26) },
      { status: 'completed', timestamp: daysAgo(25) },
    ],
  },
  {
    id: '7',
    orderId: 'ORD-2026-1018',
    customer: { name: 'Sanjay Kulkarni', phone: '+91 77777 88888', email: 'sanjay@kulkarnitextiles.in' },
    items: [{
      id: 'i7',
      categoryId: 'laser-cnc',
      categoryName: 'Laser / CNC Router Work',
      serviceName: 'Laser Acrylic Engraving (With Material)',
      quantity: 20,
      specifications: 'A5 size plaques, company name + employee name, golden fill',
      notes: 'Employee recognition awards',
      designFileName: 'award_design.pdf',
    }],
    status: 'in_production',
    deliveryMethod: 'delivery',
    quoteAmount: 16000,
    notes: 'Annual function on Oct 15th',
    adminNotes: 'Production in progress',
    createdAt: daysAgo(12),
    updatedAt: daysAgo(3),
    statusHistory: [
      { status: 'quote_requested', timestamp: daysAgo(12) },
      { status: 'quote_sent', timestamp: daysAgo(11) },
      { status: 'quote_approved', timestamp: daysAgo(10) },
      { status: 'design_confirmed', timestamp: daysAgo(8) },
      { status: 'in_production', timestamp: daysAgo(3) },
    ],
  },
  {
    id: '8',
    orderId: 'ORD-2026-1012',
    customer: { name: 'Deepak Nair', phone: '+91 90909 09090', email: 'deepak.nair@pharmacy.com' },
    items: [{
      id: 'i8',
      categoryId: 'led-board',
      categoryName: 'LED Board Making',
      serviceName: 'Glow Sign Board (LED Lights)',
      quantity: 1,
      specifications: '12 ft × 4 ft, front-lit, blue and white colour scheme',
      notes: 'Shop name sign board',
      designFileName: 'shop_sign_design.cdr',
    }],
    status: 'quote_requested',
    deliveryMethod: 'delivery',
    notes: 'Pharmacy shop sign board',
    adminNotes: '',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    statusHistory: [
      { status: 'quote_requested', timestamp: daysAgo(1) },
    ],
  },
  {
    id: '9',
    orderId: 'ORD-2026-1009',
    customer: { name: 'Meera Verma', phone: '+91 81818 18181', email: 'meera.v@events.com' },
    items: [{
      id: 'i9',
      categoryId: 'uv-eco-solvent',
      categoryName: 'UV Eco Solvent Printing',
      serviceName: 'Canvas',
      quantity: 6,
      specifications: '2 ft × 3 ft canvas prints, family portraits',
      notes: 'Wedding gift sets',
      designFileName: 'family_photos.zip',
    }],
    status: 'completed',
    deliveryMethod: 'delivery',
    quoteAmount: 5400,
    notes: '',
    adminNotes: 'Delivered',
    createdAt: daysAgo(45),
    updatedAt: daysAgo(40),
    statusHistory: [
      { status: 'quote_requested', timestamp: daysAgo(45) },
      { status: 'quote_sent', timestamp: daysAgo(44) },
      { status: 'quote_approved', timestamp: daysAgo(43) },
      { status: 'design_confirmed', timestamp: daysAgo(42) },
      { status: 'in_production', timestamp: daysAgo(42) },
      { status: 'ready', timestamp: daysAgo(41) },
      { status: 'completed', timestamp: daysAgo(40) },
    ],
  },
  {
    id: '10',
    orderId: 'ORD-2026-1004',
    customer: { name: 'Arjun Pandey', phone: '+91 72727 27272', email: 'arjun@pandeylaw.com' },
    items: [{
      id: 'i10',
      categoryId: 'other-work',
      categoryName: 'Other Work & Fabrication',
      serviceName: 'Self Inking Stamp (Round)',
      quantity: 3,
      specifications: 'Advocate stamp, 42mm round, blue ink',
      notes: 'Registered advocate rubber stamp',
    }],
    status: 'completed',
    deliveryMethod: 'pickup',
    quoteAmount: 1650,
    notes: '',
    adminNotes: 'Completed',
    createdAt: daysAgo(60),
    updatedAt: daysAgo(57),
    statusHistory: [
      { status: 'quote_requested', timestamp: daysAgo(60) },
      { status: 'quote_sent', timestamp: daysAgo(59) },
      { status: 'quote_approved', timestamp: daysAgo(58) },
      { status: 'design_confirmed', timestamp: daysAgo(58) },
      { status: 'in_production', timestamp: daysAgo(58) },
      { status: 'ready', timestamp: daysAgo(57) },
      { status: 'completed', timestamp: daysAgo(57) },
    ],
  },
  {
    id: '11',
    orderId: 'ORD-2026-1001',
    customer: { name: 'Ritu Singh', phone: '+91 63636 36363', email: 'ritu.singh@school.edu' },
    items: [{
      id: 'i11',
      categoryId: 'other-work',
      categoryName: 'Other Work & Fabrication',
      serviceName: 'Momento Acrylic Trophy',
      quantity: 50,
      specifications: 'School annual day awards, laser engraved names, 8 inch height',
      notes: 'All 50 names provided in Excel',
      designFileName: 'trophy_names.xlsx',
    }],
    status: 'design_confirmed',
    deliveryMethod: 'delivery',
    quoteAmount: 40000,
    notes: 'School annual day Oct 20',
    adminNotes: 'Design confirmed, scheduled for production',
    createdAt: daysAgo(8),
    updatedAt: daysAgo(2),
    statusHistory: [
      { status: 'quote_requested', timestamp: daysAgo(8) },
      { status: 'quote_sent', timestamp: daysAgo(7) },
      { status: 'quote_approved', timestamp: daysAgo(5) },
      { status: 'design_confirmed', timestamp: daysAgo(2) },
    ],
  },
  {
    id: '12',
    orderId: 'ORD-2026-0998',
    customer: { name: 'Vikas Rao', phone: '+91 55555 66666', email: 'vikas.rao@realestate.com' },
    items: [{
      id: 'i12',
      categoryId: 'other-work',
      categoryName: 'Other Work & Fabrication',
      serviceName: 'Acrylic Name Plate',
      quantity: 10,
      specifications: 'Office door nameplates, 10×4 inch, acrylic with golden letters',
      notes: '10 offices – names list attached',
      designFileName: 'nameplate_names.pdf',
    }],
    status: 'in_production',
    deliveryMethod: 'delivery',
    quoteAmount: 9500,
    notes: 'New office building nameplates',
    adminNotes: 'In progress',
    createdAt: daysAgo(15),
    updatedAt: daysAgo(4),
    statusHistory: [
      { status: 'quote_requested', timestamp: daysAgo(15) },
      { status: 'quote_sent', timestamp: daysAgo(14) },
      { status: 'quote_approved', timestamp: daysAgo(12) },
      { status: 'design_confirmed', timestamp: daysAgo(10) },
      { status: 'in_production', timestamp: daysAgo(4) },
    ],
  },
];

// Popular services for home page
export const popularServices = [
  { icon: Printer, name: 'Digital Printing', description: 'Colour & B&W on all paper stocks', category: 'colour-digital' as ServiceCategoryId },
  { icon: Contact, name: 'Visiting Cards', description: 'Premium cards on 300 GSM+', category: 'colour-digital' as ServiceCategoryId },
  { icon: ImageIcon, name: 'Flex & Banner', description: 'Solvent & UV large-format', category: 'solvent' as ServiceCategoryId },
  { icon: Lightbulb, name: 'LED Sign Boards', description: 'Glow, neon & channel letters', category: 'led-board' as ServiceCategoryId },
  { icon: Type, name: 'Acrylic Letters', description: '3D/2D letters for shopfronts', category: 'led-board' as ServiceCategoryId },
  { icon: Sparkles, name: 'UV Printing', description: 'Eco-solvent on vinyl, canvas', category: 'uv-eco-solvent' as ServiceCategoryId },
  { icon: Zap, name: 'Laser Cutting', description: 'Acrylic cutting & engraving', category: 'laser-cnc' as ServiceCategoryId },
  { icon: Wrench, name: 'CNC Routing', description: 'MDF, WPC, ACP precision cuts', category: 'laser-cnc' as ServiceCategoryId },
  { icon: Car, name: 'Vehicle Branding', description: 'Full & partial vehicle wraps', category: 'other-work' as ServiceCategoryId },
  { icon: Presentation, name: 'Roll-Up Standees', description: 'Aluminium standees with print', category: 'uv-eco-solvent' as ServiceCategoryId },
  { icon: Stamp, name: 'Stamps', description: 'Polymer & self-inking stamps', category: 'other-work' as ServiceCategoryId },
  { icon: PartyPopper, name: 'Event Management', description: 'Complete event branding', category: 'other-work' as ServiceCategoryId },
];

export const filterTags = [
  { id: 'all', label: 'All Services' },
  { id: 'digital', label: 'Digital Printing' },
  { id: 'offset', label: 'Offset' },
  { id: 'signage', label: 'Signage' },
  { id: 'cutting', label: 'Cutting' },
  { id: 'uv', label: 'UV Printing' },
  { id: 'fabrication', label: 'Fabrication' },
  { id: 'laser', label: 'Laser/CNC' },
  { id: 'other', label: 'Other' },
];
