const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'src', 'data', 'products.ts');
let content = fs.readFileSync(filePath, 'utf8');

const newProductsArray = `export const PRODUCTS: Product[] = [
  {
    id: 'vp-pique-bio-240',
    name: 'Signature Bio-Wash 240 GSM Pique Polo',
    slug: 'signature-bio-wash-pique-polo',
    tagline: "India's #1 Corporate Choice with Premium Waffle Texture",
    description: 'Crafted from 100% super-combed cotton with a 240 GSM heavy honeycomb pique knit. Bio-washed for zero-shrinkage, feather-soft touch, and enhanced color fastness.',
    category: 'polo',
    basePrice: 599,
    bulkPrice50: 349,
    bulkPrice100: 289,
    gsm: '240 GSM Heavy Pique',
    fabric: '100% Super Combed Bio-Wash Cotton',
    fit: 'Classic Regular / Corporate Unisex',
    moq: 1,
    availableColors: FABRIC_COLORS,
    availableCollarStyles: ['classic_ribbed', 'contrast_tipped', 'mandarin_nehru'],
    supportedMethods: ['embroidery', 'dtf_print', 'screen_print'],
    rating: 4.9,
    reviewsCount: 3840,
    badge: 'BESTSELLER',
    popularFor: 'Corporate Teams, Executive Gifting, Conference Merch',
    leadTime: '48-Hour Dispatch Available',
    features: [
      'Heavyweight 240 GSM Pique Honeycomb Weave',
      'Bio-Enzyme Washed for Zero Pilling & Shrinkage',
      'Reinforced Ribbed Collar & Cuffs with Lycra Spandex',
    ],
  },
  {
    id: 'vp-premium-tshirt',
    name: 'Premium 180 GSM Crew Neck T-Shirt',
    slug: 'premium-crew-neck-tshirt',
    tagline: 'Ultra-Soft Ring Spun Everyday Cotton',
    description: 'Our finest crew neck t-shirt for events, casual Fridays, and giveaways.',
    category: 'tshirt',
    basePrice: 449,
    bulkPrice50: 249,
    bulkPrice100: 199,
    gsm: '180 GSM Ring-Spun',
    fabric: '100% Bio-Wash Cotton',
    fit: 'Regular Unisex',
    moq: 1,
    availableColors: [FABRIC_COLORS[0], FABRIC_COLORS[4], FABRIC_COLORS[5], FABRIC_COLORS[6]],
    availableCollarStyles: [],
    supportedMethods: ['dtf_print', 'screen_print'],
    rating: 4.8,
    reviewsCount: 4210,
    badge: 'POPULAR EVENT MERCH',
    popularFor: 'Hackathons, Trade Shows, NGO Events',
    leadTime: '24-Hour Dispatch',
    features: ['Shoulder-to-shoulder taping', 'Seamless double needle collar'],
  },
  {
    id: 'vp-coffee-mug',
    name: 'Custom Ceramic Coffee Mug (330ml)',
    slug: 'custom-ceramic-coffee-mug',
    tagline: 'The Classic Desk Companion',
    description: 'High-quality 11oz ceramic mug with vibrant sublimation printing. Microwave and dishwasher safe.',
    category: 'drinkware',
    basePrice: 299,
    bulkPrice50: 149,
    bulkPrice100: 119,
    moq: 10,
    availableColors: [FABRIC_COLORS[5], FABRIC_COLORS[4]],
    supportedMethods: ['dtf_print'],
    rating: 4.7,
    reviewsCount: 1540,
    popularFor: 'Welcome Kits, Employee Gifts, Office Desks',
    leadTime: '48-Hour Dispatch',
    features: ['330ml Capacity', 'Microwave Safe', 'High-Gloss Finish'],
  },
  {
    id: 'vp-canvas-tote',
    name: 'Heavy Duty 300 GSM Canvas Tote Bag',
    slug: 'heavy-duty-canvas-tote',
    tagline: 'Eco-friendly Reusable Carry-All',
    description: 'Durable and spacious tote bag made from natural canvas. Excellent printing surface for large logos.',
    category: 'bag',
    basePrice: 199,
    bulkPrice50: 129,
    bulkPrice100: 99,
    moq: 20,
    availableColors: [FABRIC_COLORS[5], FABRIC_COLORS[0]],
    supportedMethods: ['screen_print', 'dtf_print'],
    rating: 4.9,
    reviewsCount: 890,
    badge: 'ECO-FRIENDLY 🌱',
    popularFor: 'Exhibitions, Retail Packaging, Sustainable Swag',
    leadTime: '3-4 Business Days',
    features: ['Reinforced Webbing Handles', 'Large 12x14 inch print area'],
  },
  {
    id: 'vp-thermos-flask',
    name: 'Matte Black Temperature Water Bottle (750ml)',
    slug: 'temperature-water-bottle-flask',
    tagline: 'Hot for 12 Hours, Cold for 24 Hours',
    description: 'Premium double-walled vacuum insulated stainless steel flask with precision laser engraving.',
    category: 'drinkware',
    basePrice: 799,
    bulkPrice50: 499,
    bulkPrice100: 399,
    moq: 10,
    availableColors: [FABRIC_COLORS[4], FABRIC_COLORS[1]],
    supportedMethods: ['dtf_print'],
    rating: 4.9,
    reviewsCount: 1120,
    badge: 'PREMIUM GIFT',
    popularFor: 'Executive Hampers, Travel Swag, VIP Clients',
    leadTime: '5-7 Business Days',
    features: ['Double-Wall Vacuum Insulation', 'Leak-Proof Cap', 'Laser Engraving Support'],
  },
  {
    id: 'vp-pu-diary',
    name: 'Premium Hardbound PU Leather Diary',
    slug: 'premium-hardbound-leather-diary',
    tagline: 'Executive A5 Notebook with Debossed Logo',
    description: 'Soft-touch vegan leather cover with 192 ruled ivory pages, elastic band, and ribbon bookmark.',
    category: 'stationery',
    basePrice: 349,
    bulkPrice50: 229,
    bulkPrice100: 189,
    moq: 20,
    availableColors: [FABRIC_COLORS[0], FABRIC_COLORS[4], FABRIC_COLORS[10]],
    supportedMethods: ['dtf_print', 'screen_print'],
    rating: 4.8,
    reviewsCount: 1430,
    popularFor: 'New Joinees, Leadership Seminars, Year-end Gifts',
    leadTime: '5 Business Days',
    features: ['A5 Size (14.8 x 21 cm)', '192 Ruled Pages (80 GSM)', 'Gold Foil / Deboss Friendly'],
  },
  {
    id: 'vp-swag-onboarding-box',
    name: 'Custom Corporate Swag Onboarding Kit',
    slug: 'custom-corporate-swag-onboarding-kit',
    tagline: 'The Ultimate Employee Welcome & Client Hampers Box',
    description: 'Complete customized welcome kit including 1x Bio-Wash Polo, 1x Flask, 1x PU Diary, 1x Metal Pen, and 1x Custom Logo Box.',
    category: 'swag_box',
    basePrice: 1499,
    bulkPrice50: 899,
    bulkPrice100: 749,
    moq: 5,
    availableColors: [FABRIC_COLORS[0], FABRIC_COLORS[4], FABRIC_COLORS[5]],
    availableCollarStyles: ['classic_ribbed'],
    supportedMethods: ['embroidery', 'dtf_print'],
    rating: 4.97,
    reviewsCount: 2600,
    badge: 'CORPORATE FAVORITE 🎁',
    popularFor: 'New Hire Day 1 Welcome Kits, Annual Day Hampers, VIP Gifting',
    leadTime: '3-5 Business Days',
    features: [
      'Includes 5 Customized Branded Products in 1 Rigid Magnetic Box',
      'Individual Employee Direct-to-Door Delivery Available',
      'Free Digital Proof & Swatch Box for Orders >50 kits',
    ],
  },
];`;

const startIndex = content.indexOf('export const PRODUCTS: Product[] = [');
const endIndex = content.indexOf('export const CLIENT_LOGOS = [');

if (startIndex !== -1 && endIndex !== -1) {
  content = content.slice(0, startIndex) + newProductsArray + '\n\n' + content.slice(endIndex);
  fs.writeFileSync(filePath, content);
  console.log('Successfully updated PRODUCTS');
} else {
  console.log('Could not find boundaries');
}
